config/routes.rb
SnInvit::Application.routes.draw do
  resources :replies do
    collection do
      get "myreplies/:id" => "replies#index", as: :myreplies
    end
  end
  resources :blessings do
    collection do
      get "myblessings/:id" => "blessings#index", as: :myblessings
    end
  end

  resources :events do
    collection do
      get ":id" => "events#index", as: :myevents
      get "destroy_event/:id" => "events#destroy_event", as: "destroy_event"
    end
  end

  resources :invitations do
    collection do
      get "galery/:id" => "invitations#galery", as: :myphotos

      post "add_attachement/:id" => "invitations#add_attachement", as: :add_attachement
      get "destroy_attachement/:id" => "invitations#destroy_attachement", as: :destroy_attachement
    end
  end

  get 'app/:invitation_id/:event_type/initialize' => 'home#app'
  get 'app/:invitation_id/blessings' => 'blessings#app_list'
  get 'app/:invitation_id/blessings/add' => 'blessings#app_add'
  get 'app/:invitation_id/replies/add' => 'replies#app_add'
  get 'app/:invitation_id/music' => 'home#music'

  devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)
  devise_for :users
  get "dashboard" => 'users#show', as: "user"
  get "settings" => 'users#settings', as: "user_settings"
  root to: "home#index"

end

app/views/shared/_blue_navbar.html.erb
<div class="navbar navbar-default" id="navbar">
  <script type="text/javascript">
    try{ace.settings.check('navbar' , 'fixed')}catch(e){}
  </script>

  <div class="navbar-container" id="navbar-container">
    <div class="navbar-header pull-left">
      <a href="#" class="navbar-brand">
        <small>
          <i class="icon-leaf"></i>
          <%= Rails.application.config.appname %>
        </small>
      </a><!-- /.brand -->
    </div><!-- /.navbar-header -->

    <div class="navbar-header pull-right" role="navigation">
      <ul class="nav ace-nav">
        <li class="grey">
          <a data-toggle="dropdown" class="dropdown-toggle" href="#">
            <i class="icon-tasks"></i>
            <span class="badge badge-grey">4</span>
          </a>

          <ul class="pull-right dropdown-navbar dropdown-menu dropdown-caret dropdown-close">
            <li class="dropdown-header">
              <i class="icon-ok"></i>
              4 Tasks to complete
            </li>

            <li>
              <a href="#">
                <div class="clearfix">
                  <span class="pull-left">Software Update</span>
                  <span class="pull-right">65%</span>
                </div>

                <div class="progress progress-mini ">
                  <div style="width:65%" class="progress-bar "></div>
                </div>
              </a>
            </li>

            <li>
              <a href="#">
                <div class="clearfix">
                  <span class="pull-left">Hardware Upgrade</span>
                  <span class="pull-right">35%</span>
                </div>

                <div class="progress progress-mini ">
                  <div style="width:35%" class="progress-bar progress-bar-danger"></div>
                </div>
              </a>
            </li>

            <li>
              <a href="#">
                <div class="clearfix">
                  <span class="pull-left">Unit Testing</span>
                  <span class="pull-right">15%</span>
                </div>

                <div class="progress progress-mini ">
                  <div style="width:15%" class="progress-bar progress-bar-warning"></div>
                </div>
              </a>
            </li>

            <li>
              <a href="#">
                <div class="clearfix">
                  <span class="pull-left">Bug Fixes</span>
                  <span class="pull-right">90%</span>
                </div>

                <div class="progress progress-mini progress-striped active">
                  <div style="width:90%" class="progress-bar progress-bar-success"></div>
                </div>
              </a>
            </li>

            <li>
              <a href="#">
                See tasks with details
                <i class="icon-arrow-right"></i>
              </a>
            </li>
          </ul>
        </li>

        <li class="purple">
          <a data-toggle="dropdown" class="dropdown-toggle" href="#">
            <i class="icon-bell-alt icon-animated-bell"></i>
            <span class="badge badge-important">8</span>
          </a>

          <ul class="pull-right dropdown-navbar navbar-pink dropdown-menu dropdown-caret dropdown-close">
            <li class="dropdown-header">
              <i class="icon-warning-sign"></i>
              8 Notifications
            </li>

            <li>
              <a href="#">
                <div class="clearfix">
                  <span class="pull-left">
                    <i class="btn btn-xs no-hover btn-pink icon-comment"></i>
                    New Comments
                  </span>
                  <span class="pull-right badge badge-info">+12</span>
                </div>
              </a>
            </li>

            <li>
              <a href="#">
                <i class="btn btn-xs btn-primary icon-user"></i>
                Bob just signed up as an editor ...
              </a>
            </li>

            <li>
              <a href="#">
                <div class="clearfix">
                  <span class="pull-left">
                    <i class="btn btn-xs no-hover btn-success icon-shopping-cart"></i>
                    New Orders
                  </span>
                  <span class="pull-right badge badge-success">+8</span>
                </div>
              </a>
            </li>

            <li>
              <a href="#">
                <div class="clearfix">
                  <span class="pull-left">
                    <i class="btn btn-xs no-hover btn-info icon-twitter"></i>
                    Followers
                  </span>
                  <span class="pull-right badge badge-info">+11</span>
                </div>
              </a>
            </li>

            <li>
              <a href="#">
                See all notifications
                <i class="icon-arrow-right"></i>
              </a>
            </li>
          </ul>
        </li>

        <li class="green">
          <a data-toggle="dropdown" class="dropdown-toggle" href="#">
            <i class="icon-envelope icon-animated-vertical"></i>
            <span class="badge badge-success">5</span>
          </a>

          <ul class="pull-right dropdown-navbar dropdown-menu dropdown-caret dropdown-close">
            <li class="dropdown-header">
              <i class="icon-envelope-alt"></i>
              5 Messages
            </li>

            <li>
              <a href="#">
                <img src="/assets/avatar.png" class="msg-photo" alt="Alex's Avatar" />
                <span class="msg-body">
                  <span class="msg-title">
                    <span class="blue">Alex:</span>
                    Ciao sociis natoque penatibus et auctor ...
                  </span>

                  <span class="msg-time">
                    <i class="icon-time"></i>
                    <span>a moment ago</span>
                  </span>
                </span>
              </a>
            </li>

            <li>
              <a href="#">
                <img src="/assets/avatar3.png" class="msg-photo" alt="Susan's Avatar" />
                <span class="msg-body">
                  <span class="msg-title">
                    <span class="blue">Susan:</span>
                    Vestibulum id ligula porta felis euismod ...
                  </span>

                  <span class="msg-time">
                    <i class="icon-time"></i>
                    <span>20 minutes ago</span>
                  </span>
                </span>
              </a>
            </li>

            <li>
              <a href="#">
                <img src="/assets/avatar4.png" class="msg-photo" alt="Bob's Avatar" />
                <span class="msg-body">
                  <span class="msg-title">
                    <span class="blue">Bob:</span>
                    Nullam quis risus eget urna mollis ornare ...
                  </span>

                  <span class="msg-time">
                    <i class="icon-time"></i>
                    <span>3:15 pm</span>
                  </span>
                </span>
              </a>
            </li>

            <li>
              <a href="inbox.html">
                See all messages
                <i class="icon-arrow-right"></i>
              </a>
            </li>
          </ul>
        </li>

        <li class="light-blue">
          <a data-toggle="dropdown" href="#" class="dropdown-toggle">
            <img class="nav-user-photo" src="/assets/avatar2.png" alt="<%= current_user.username %>'s Photo" />
            <span class="user-info">
              <small>Welcome,</small>
              <%= current_user.username %>
            </span>

            <i class="icon-caret-down"></i>
          </a>

          <ul class="user-menu pull-right dropdown-menu dropdown-yellow dropdown-caret dropdown-close">
            <li>
              <a href="#">
                <i class="icon-cog"></i>
                NIY
              </a>
            </li>

            <li>
              <a href="#">
                <i class="icon-user"></i>
                NIY
              </a>
            </li>

            <li class="divider"></li>

            <li>
              <a href="<%= destroy_user_session_path %>" data-method='delete' rel="nofollow">
                <i class="icon-off"></i>
                Logout
              </a>
            </li>
          </ul>
        </li>
      </ul><!-- /.ace-nav -->
    </div><!-- /.navbar-header -->
  </div><!-- /.container -->
</div>

app/views/shared/_left_navigation.html.erb
<ul class="nav nav-list">
  <li class="<%= "active" if params[:controller] == "users" &&  params[:action] == "show" %>">
    <a href="<%= user_path  %>">
      <i class="icon-dashboard"></i>
      <span class="menu-text"> Dashboard </span>
    </a>
  </li>

<% current_user.invitations.each do |inv| %>

   <li class="<%= "active open" if params[:id].to_i == inv.id %>">
    <a href="#" class="dropdown-toggle">
      <i class="icon-file-alt"></i>

      <span class="menu-text">
        <%= inv.name %>
      </span>

      <b class="arrow icon-angle-down"></b>
    </a>

    <ul class="submenu">
      <li class="<%= "active" if params[:controller] == "invitations" && params[:action] == "show" &&  params[:id].to_i == inv.id %>">
        <a href="<%= invitation_path(inv)  %>">
          <i class="icon-double-angle-right"></i>
          <%= t :overview %>
        </a>
      </li>
      <li class="<%= "active" if params[:controller] == "invitations" && params[:action] == "edit" &&  params[:id].to_i == inv.id %>">
        <a href="<%= edit_invitation_path(inv)  %>">
          <i class="icon-double-angle-right"></i>
          <%= t :general_info %>
        </a>
      </li>
      <li class="<%= "active" if params[:controller] == "events" && params[:action] == "index" &&  params[:id].to_i == inv.id %>">
        <a href="<%= myevents_events_path(inv)  %>">
          <i class="icon-double-angle-right"></i>
          <%= t :events %>
        </a>
      </li>
      <li class="<%= "active" if params[:controller] == "invitations" && params[:action] == "galery" &&  params[:id].to_i == inv.id %>">
        <a href="<%= myphotos_invitations_path(inv)  %>">
          <i class="icon-double-angle-right"></i>
          <%= t :my_photos %>
        </a>
      </li>
      <li class="<%= "active" if params[:controller] == "replies" && params[:action] == "index" &&  params[:id].to_i == inv.id %>">
        <a href="<%= myreplies_replies_path(inv)  %>">
          <i class="icon-double-angle-right"></i>
          <%= t :my_replies %>
        </a>
      </li>
      <li class="<%= "active" if params[:controller] == "blessings" && params[:action] == "index" &&  params[:id].to_i == inv.id %>">
        <a href="<%=  myblessings_blessings_path(inv)  %>">
          <i class="icon-double-angle-right"></i>
          <%= t :my_blessings %>
        </a>
      </li>
    </ul>
  </li>

<% end -%>
  <li class="<%= "active" if params[:controller] == "users" &&  params[:action] == "settings" %>">
    <a href="<%= user_settings_path  %>">
      <i class="icon-text-width"></i>
      <span class="menu-text"> Settings </span>
    </a>
  </li>


</ul><!-- /.nav-list -->

app/views/shared/_sidebar_shortcuts.html.erb
<div class="sidebar-shortcuts" id="sidebar-shortcuts">
  <div class="sidebar-shortcuts-large" id="sidebar-shortcuts-large">


    <button class="btn btn-info" id="new_app_btn">
      <i class="icon-plus"></i>
      <span class="menu-text"> <%= t :new_app %> </span>
    </button>

  </div>

  <div class="sidebar-shortcuts-mini" id="sidebar-shortcuts-mini">
    <span class="btn btn-success"></span>

    <span class="btn btn-info"></span>

    <span class="btn btn-warning"></span>

    <span class="btn btn-danger"></span>
  </div>
</div><!-- #sidebar-shortcuts -->