config/routes.rb
SnInvit::Application.routes.draw do
  resources :replies do
    collection do
      get "myreplies/:id" => "replies#index", as: :myreplies
    end
  end
  resources :blessings do
    collection do
      get "myblessings/:id" => "blessings#index", as: :myblessings
    end
  end

  resources :events do
    collection do
      get ":id" => "events#index", as: :myevents
      get "destroy_event/:id" => "events#destroy_event", as: "destroy_event"
    end
  end

  resources :invitations do
    collection do
      get "galery/:id" => "invitations#galery", as: :myphotos

      post "add_attachement/:id" => "invitations#add_attachement", as: :add_attachement
      get "destroy_attachement/:id" => "invitations#destroy_attachement", as: :destroy_attachement
    end
  end

  get 'app/:invitation_id/:event_type/initialize' => 'home#app'
  get 'app/:invitation_id/blessings' => 'blessings#app_list'
  get 'app/:invitation_id/blessings/add' => 'blessings#app_add'
  get 'app/:invitation_id/replies/add' => 'replies#app_add'
  get 'app/:invitation_id/music' => 'home#music'

  devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)
  devise_for :users
  get "dashboard" => 'users#show', as: "user"
  get "settings" => 'users#settings', as: "user_settings"
  root to: "home#index"

end

app/models/event.rb
# == Schema Information
#
# Table name: events
#
#  id            :integer          not null, primary key
#  name          :string(255)
#  address       :text
#  longitude     :float
#  latitude      :float
#  eventtime     :datetime
#  phone         :string(255)
#  invitation_id :integer
#  created_at    :datetime
#  updated_at    :datetime
#

class Event < ActiveRecord::Base
  belongs_to :invitation
  validates :name, :address, :longitude, :latitude, :eventtime, presence: true

  def as_json(options=nil)
    item = super({ only: [
        :id, :name, :address, :longitude, :latitude, :eventtime, :phone
    ] }.merge(options || {}))
    item.merge({
      eventmoment: self.eventtime.strftime("%m月%d日 %H:%M")
    })
  end
end

app/controllers/events_controller.rb
class EventsController < InheritedResources::Base
  before_filter :authenticate_user!, except: [:app_list]
  before_filter :sandbox_user_using_invitataion_id, except: [:create, :new, :destroy, :destroy_event]
  before_filter :verifyinvitationid, only: [:create]

  def index
    @events = @invitation.events
    @event = Event.new
  end

  def create
    super do |format|
      format.html { redirect_to :back}
    end
  end

  def destroy_event
    destroy
  end

  def destroy
    super do |format|
      format.html { redirect_to :back}
    end
  end

  private
  def permitted_params
    params.permit!
  end

  def verifyinvitationid
    inv = Invitation.find(params[:event][:invitation_id])
    if inv.user_id != current_user.id
      redirect_to root_url, flash: {error: "Please don't cross user sandbox."}
    end
  end
end

app/helpers/events_helper.rb
module EventsHelper
end

app/views/events/_form.html.erb
<%= form_for(@event) do |f| %>
  <% if @event.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@event.errors.count, "error") %> prohibited this event from being saved:</h2>

      <ul>
      <% @event.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br>
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :address %><br>
    <%= f.text_area :address %>
  </div>
  <div class="field">
    <%= f.label :longitude %><br>
    <%= f.text_field :longitude %>
  </div>
  <div class="field">
    <%= f.label :latitude %><br>
    <%= f.text_field :latitude %>
  </div>
  <div class="field">
    <%= f.label :eventtime %><br>
    <%= f.datetime_select :eventtime %>
  </div>
  <div class="field">
    <%= f.label :phone %><br>
    <%= f.text_field :phone %>
  </div>
  <div class="field">
    <%= f.label :invitation_id %><br>
    <%= f.text_field :invitation_id %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/events/edit.html.erb
<h1>Editing event</h1>

<%= render 'form' %>

<%= link_to 'Show', @event %> |
<%= link_to 'Back', events_path %>

app/views/events/index.html.erb
<div class="page-header">
  <h1>
    Event
    <small>
      <i class="icon-double-angle-right"></i>
      Your mariage events
    </small>
  </h1>

</div>


<a class="btn btn-primary"  data-toggle="modal" role="button" href="#modal-form">
  <i class="icon-plus align-top bigger-125"></i>
   <%= t :new_event %>
</a>

<% @events.each_with_index do |e, i| %>
  <div class="widget-box">
      <div class="widget-header">
        <h4><%= "#{t(:event)} #{i+1} - #{e.name}" %></h4>

        <span class="widget-toolbar">
          <a href="#" data-action="collapse">
            <i class="icon-chevron-up"></i>
          </a>
          <%= link_to(destroy_event_events_path(e)) do %>
            <i class="icon-remove red"></i>
          <% end -%>
        </span>
      </div>

      <div class="widget-body">
        <div class="widget-main">

            <span class="lbl"><%= debug e %></span>
        </div>
      </div>
    </div>
<% end -%>
<%= form_for @event do | f | %>
<div id="modal-form" class="modal" tabindex="-1">
  <div class="modal-dialog">
    <div class="modal-content">
      <div class="modal-header">
        <button type="button" class="close" data-dismiss="modal">&times;</button>
        <h4 class="blue bigger">Please fill the following form fields (Every field is required!)</h4>
      </div>
      <div class="modal-body overflow-visible">
        <div class="row">
          <div class="col-xs-12">
            <div class="space-4"></div>
            <div class="form-group">
              <div class="col-sm-3">
                <label><%= t :name %></label>
              </div>
              <div class="col-sm-9 ">
                <%= f.text_field :name, class: "col-xs-12" , placeholder: t(:name)%>
              </div>
              <%= f.hidden_field :invitation_id, value: params[:id]%>
              <div>
                <div class="form-group">
                  <div class="col-sm-3">
                    <label class="control-label no-padding-right"><%= t :address %></label>
                  </div>

                  <div class="col-sm-9 ">
                    <%= f.text_field :address, class: "col-xs-12" , placeholder: t(:address) %>
                  </div>
                </div>

                <div class="form-group">
                  <div class="col-sm-3">
                    <label class="control-label no-padding-right"><%= t :cordinate %></label>
                  </div>
                  <div class="col-sm-9 ">
                  <%= f.text_field :longitude, class: "col-xs-6", placeholder: t(:longitude) %><%= f.text_field :latitude, class: "col-xs-6", placeholder: t(:latitude) %>
                  </div>
                </div>
                <div class="form-group">
                  <div class="col-sm-3">
                    <label class="control-label no-padding-right"><%= t :phone %></label>
                  </div>
                  <div class="col-sm-9 ">
                    <%= f.text_field :phone, class: "col-xs-12" , placeholder: t(:phone)%>
                  </div>
                </div>
                <div class="form-group">
                  <div class="col-sm-3">
                    <label class="control-label no-padding-right"><%= t :event_time %></label>
                  </div>
                  <div class="col-sm-9 ">
                    <%= f.text_field :eventtime, class: "col-xs-12" , placeholder: t(:event_time), id: "eventtimeinput", :"data-format" => "dd/MM/yyyy hh:mm:ss" %>
                  </div>
                </div>
                <div class="form-group">
                  <div class="col-sm-3">
                    <label class="control-label no-padding-right"><%= t :is_diner %></label>
                  </div>
                  <div class="col-sm-9 ">
                    <%= f.check_box :is_diner, class: "col-xs-1" %>
                  </div>
                </div>
              </div>
            </div>
          </div>
        </div>
      </div>

      <div class="modal-footer">
        <button class="btn btn-sm" data-dismiss="modal">
          <i class="icon-remove"></i>
          Cancel
        </button>
        <%= f.submit class: "btn btn-sm btn-primary", id: "event_submit" %>
      </div>
    </div>
  </div>
  <% end -%>

app/views/events/new.html.erb
<h1>New event</h1>

<%= render 'form' %>

<%= link_to 'Back', events_path %>

app/views/events/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @event.name %>
</p>

<p>
  <strong>Address:</strong>
  <%= @event.address %>
</p>

<p>
  <strong>Longitude:</strong>
  <%= @event.longitude %>
</p>

<p>
  <strong>Latitude:</strong>
  <%= @event.latitude %>
</p>

<p>
  <strong>Eventtime:</strong>
  <%= @event.eventtime %>
</p>

<p>
  <strong>Phone:</strong>
  <%= @event.phone %>
</p>

<p>
  <strong>Invitation:</strong>
  <%= @event.invitation %>
</p>

<%= link_to 'Edit', edit_event_path(@event) %> |
<%= link_to 'Back', events_path %>