config/routes.rb
SnInvit::Application.routes.draw do
  resources :replies do
    collection do
      get "myreplies/:id" => "replies#index", as: :myreplies
    end
  end
  resources :blessings do
    collection do
      get "myblessings/:id" => "blessings#index", as: :myblessings
    end
  end

  resources :events do
    collection do
      get ":id" => "events#index", as: :myevents
      get "destroy_event/:id" => "events#destroy_event", as: "destroy_event"
    end
  end

  resources :invitations do
    collection do
      get "galery/:id" => "invitations#galery", as: :myphotos

      post "add_attachement/:id" => "invitations#add_attachement", as: :add_attachement
      get "destroy_attachement/:id" => "invitations#destroy_attachement", as: :destroy_attachement
    end
  end

  get 'app/:invitation_id/:event_type/initialize' => 'home#app'
  get 'app/:invitation_id/blessings' => 'blessings#app_list'
  get 'app/:invitation_id/blessings/add' => 'blessings#app_add'
  get 'app/:invitation_id/replies/add' => 'replies#app_add'
  get 'app/:invitation_id/music' => 'home#music'

  devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)
  devise_for :users
  get "dashboard" => 'users#show', as: "user"
  get "settings" => 'users#settings', as: "user_settings"
  root to: "home#index"

end

app/models/invitation.rb
# == Schema Information
#
# Table name: invitations
#
#  id                   :integer          not null, primary key
#  bride                :string(255)
#  groom                :string(255)
#  weddingday           :date
#  theme                :string(255)
#  user_id              :integer
#  created_at           :datetime
#  updated_at           :datetime
#  name                 :string(255)
#  welcomemsg           :string(255)
#  bgmusic_file_name    :string(255)
#  bgmusic_content_type :string(255)
#  bgmusic_file_size    :integer
#  bgmusic_updated_at   :datetime
#

class Invitation < ActiveRecord::Base
  belongs_to :user
  validates :name, :presence => true
  has_many :replies
  has_many :blessings
  has_many :attachements
  has_many :events
  has_attached_file :bgmusic

  #validates_attachment_presence :bgmusic
  validates_attachment_content_type :bgmusic, :content_type => [ 'application/mp3', 'application/x-mp3', 'audio/mpeg', 'audio/mp3', 'application/octet-stream' ],
                                    :message => 'file must be of filetype .mp3'
  validates_attachment_size :bgmusic, :less_than => 5.megabytes

  def as_json(options=nil)
    item = super({ only: [:groom, :bride, :weddingday, :welcomemsg, :theme] }.merge(options || {}))
    item.merge({
      music: self.bgmusic.url(),
      ldate: I18n.l(self.weddingday),
      subdate: I18n.l(self.weddingday, :format => '%A')
    })
  end
end

app/controllers/invitations_controller.rb
class InvitationsController < InheritedResources::Base
  # require 'rqrcode'
  before_filter :authenticate_user!
  before_filter :sandbox_user_using_invitataion_id, except: [:create, :new, :destroy_attachement]
  before_filter :gen_qrcode, only: [:show]

  def galery
    @photo = Attachement.new
    @photos = @invitation.attachements
  end

  def add_attachement
    @attachement = @invitation.attachements.new(params.require(:attachement).permit(:image, :name))
    if @attachement.save
      redirect_to :back, flash: { success: t(:photo_created) }
    else
      redirect_to :back, flash: { error: t(:photo_create_error) }
    end
  end

  def destroy_attachement
    @attachement = Attachement.find(params[:id])
    if @attachement.invitation.user_id == current_user.id
      @attachement.destroy
      redirect_to :back
    else
      redirect_to root_url, flash: {error: "Please don't cross user sandbox."}
    end
  end

private
  def gen_qrcode
    ui_path = Rails.env.development? ? ("roc_dist/") : ("i/")
    url =  "http://#{request.host}:#{request.port}/#{ui_path}?e=f"
    logger.debug "[DEBUG] ZZZZZZZZZZZZZZZZZZZZZZZZZ  #{url}"
    @fullqr = RQRCode::QRCode.new(url, :size => 5, :level => :h )
    @diner_only = RQRCode::QRCode.new( "http://#{request.host}:#{request.port}/#{ui_path}", :size => 5, :level => :h )
  end

  def permitted_params

    params.permit!
  end
end

app/helpers/invitations_helper.rb
module InvitationsHelper
end

app/views/invitations/_form.html.erb
<%= form_for(@invitation) do |f| %>
  <% if @invitation.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@invitation.errors.count, "error") %> prohibited this invitation from being saved:</h2>

      <ul>
      <% @invitation.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>
  <div class="field">
    <%= f.label :name %><br>
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :bride %><br>
    <%= f.text_field :bride %>
  </div>
  <div class="field">
    <%= f.label :groom %><br>
    <%= f.text_field :groom %>
  </div>
  <div class="field">
    <%= f.label :weddingday %><br>
    <%= f.date_select :weddingday %>
  </div>
  <div class="field">
    <%= f.label :theme %><br>
    <%= f.text_field :theme %>
  </div>

  <div class="field">
    <%= f.label :welcomemsg %><br>
    <%= f.text_area :welcomemsg, size: "60x10" %>
  </div>

  <div class="field">
    <%= f.label :bgmusic %><br>
    <%= f.file_field :bgmusic %>
  </div>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/invitations/edit.html.erb
<h1>Editing invitation</h1>

<%= render 'form' %>

<%= link_to 'Show', @invitation %> |
<%= link_to 'Back', invitations_path %>

app/views/invitations/galery.html.erb
              <div class="page-header">
              <h1>
                Gallery
                <small>
                  <i class="icon-double-angle-right"></i>
                  responsive photo gallery using colorbox
                </small>
              </h1>

            </div>

              <div class="row-fluid">
                  <ul class="ace-thumbnails">
                  <li>
                   <a class="btn btn-app btn-info"  data-toggle="modal" role="button" href="#modal-form">
                   <i class="icon-plus bigger-230"></i>
                        <%= t :new %>
                    </a>
                    <% @photos.each do |p| %>
                    <li>
                      <a href="<%= p.image.url(:original) %>" data-rel="colorbox">
                        <img alt="150x150" src="<%= p.image.url(:thumb) %>" />
                        <div class="text">
                          <div class="inner"><%= p.name %> </div>
                        </div>
                      </a>

                      <div class="tools tools-bottom">
<!--                         <a href="#">
                          <i class="icon-link"></i>
                        </a>

                        <a href="#">
                          <i class="icon-paper-clip"></i>
                        </a>

                        <a href="#">
                          <i class="icon-pencil"></i>
                        </a>
 -->
                         <a href="<%= destroy_attachement_invitations_path(p.id) %>">
                        <i class="icon-remove red"></i>

                        </a>
                      </div>
                    </li>
                    <% end -%>

                  </ul>
                </div>


            <%= form_for @photo, url: {controller: "invitations", action: "add_attachement"} do | f | %>
                <div id="modal-form" class="modal" tabindex="-1">
                  <div class="modal-dialog">
                    <div class="modal-content">
                      <div class="modal-header">
                        <button type="button" class="close" data-dismiss="modal">&times;</button>
                        <h4 class="blue bigger">Please fill the following form fields</h4>
                      </div>
                      <div class="modal-body overflow-visible">
                        <div class="row">

                          <div class="col-xs-12 col-sm-5">
                              <div class="space"></div>
                                <%= f.file_field :image, id: "gallery_new_img_input" %>
                              </div>
                              <div class="col-xs-12 col-sm-7">
                                  <div class="space-4"></div>
                                  <div class="form-group">
                                    <label for="form-field-username">Username</label>
                                  <div>
                                <%= f.text_field :name, class: "input-large" %>

                              </div>
                          </div>
                        </div>
                      </div>
                        </div>
                      </div>

                      <div class="modal-footer">
                        <button class="btn btn-sm" data-dismiss="modal">
                          <i class="icon-remove"></i>
                          Cancel
                        </button>
                        <%= f.submit class: "btn btn-sm btn-primary" %>

                      </div>
                    </div>
                  </div>
                <% end -%>

app/views/invitations/index.html.erb
<h1>New invitation</h1>

<%= render 'form' %>

<%= link_to 'Back', invitations_path %>

app/views/invitations/new.html.erb
<h1>New invitation</h1>

<%= render 'form' %>

<%= link_to 'Back', invitations_path %>

app/views/invitations/show.html.erb
<p id="notice"><%= notice %></p>
<p>
  <strong>Id:</strong>
  <%= @invitation.id %>
</p>


<p>
  <strong>Name:</strong>
  <%= @invitation.name %>
</p>


<p>
  <strong>Bride:</strong>
  <%= @invitation.bride %>
</p>

<p>
  <strong>Groom:</strong>
  <%= @invitation.groom %>
</p>

<p>
  <strong>Weddingday:</strong>
  <%= @invitation.weddingday %>
</p>

<p>
  <strong>Theme:</strong>
  <%= @invitation.theme %>
</p>

<p>
  <strong>User:</strong>
  <%= @invitation.user.username %>
</p>

<p>
<strong>Full Invit qrcode:</strong>
<style type="text/css">
table {
  border-width: 0;
  border-style: none;
  border-color: #0000ff;
  border-collapse: collapse;
}
td {
  border-width: 0;
  border-style: none;
  border-color: #0000ff;
  border-collapse: collapse;
  padding: 0;
  margin: 0;
  width: 10px;
  height: 10px;
}
td.black { background-color: #000; }
td.white { background-color: #fff; }
</style>

<table>
<% @fullqr.modules.each_index do |x| %>
  <tr>
  <% @fullqr.modules.each_index do |y| %>
   <% if @fullqr.dark?(x,y) %>
    <td class="black"/>
   <% else %>
    <td class="white"/>
   <% end %>
  <% end %>
  </tr>
<% end %>
</table>
</p>
<br><br><br><br><br>
<p>
<strong>Diner only Invit qrcode: </strong>

<table>
<% @diner_only.modules.each_index do |x| %>
  <tr>
  <% @diner_only.modules.each_index do |y| %>
   <% if @diner_only.dark?(x,y) %>
    <td class="black"/>
   <% else %>
    <td class="white"/>
   <% end %>
  <% end %>
  </tr>
<% end %>
</table>
</p>

<%= link_to 'Edit', edit_invitation_path(@invitation) %> |
<%= link_to 'Back', invitations_path %>