config/routes.rb
SnInvit::Application.routes.draw do
  resources :replies do
    collection do
      get "myreplies/:id" => "replies#index", as: :myreplies
    end
  end
  resources :blessings do
    collection do
      get "myblessings/:id" => "blessings#index", as: :myblessings
    end
  end

  resources :events do
    collection do
      get ":id" => "events#index", as: :myevents
      get "destroy_event/:id" => "events#destroy_event", as: "destroy_event"
    end
  end

  resources :invitations do
    collection do
      get "galery/:id" => "invitations#galery", as: :myphotos

      post "add_attachement/:id" => "invitations#add_attachement", as: :add_attachement
      get "destroy_attachement/:id" => "invitations#destroy_attachement", as: :destroy_attachement
    end
  end

  get 'app/:invitation_id/:event_type/initialize' => 'home#app'
  get 'app/:invitation_id/blessings' => 'blessings#app_list'
  get 'app/:invitation_id/blessings/add' => 'blessings#app_add'
  get 'app/:invitation_id/replies/add' => 'replies#app_add'
  get 'app/:invitation_id/music' => 'home#music'

  devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)
  devise_for :users
  get "dashboard" => 'users#show', as: "user"
  get "settings" => 'users#settings', as: "user_settings"
  root to: "home#index"

end

app/models/blessing.rb
# == Schema Information
#
# Table name: blessings
#
#  id            :integer          not null, primary key
#  content       :text
#  name          :string(255)
#  invitation_id :integer
#  created_at    :datetime
#  updated_at    :datetime
#

class Blessing < ActiveRecord::Base
  belongs_to :invitation
end

app/controllers/blessings_controller.rb
class BlessingsController < InheritedResources::Base
  before_filter :authenticate_user!, except: [:app_list, :app_add]
  before_filter :sandbox_user_using_invitataion_id, only: [:index]
  def index
    @blessings = @invitation.blessings
  end

  def app_list
    skip = params[:start] ? params[:start].to_i : 0
    limit = params[:limit] ? params[:limit].to_i : 10

    @invitation = Invitation.find(params[:invitation_id])
    @blessings = @invitation.blessings
    @total = @blessings.count()
    @blessings = @blessings.limit(limit).offset(skip).order('created_at DESC')
  end

  def app_add
    @invitation = Invitation.find(params[:invitation_id])
    @blessing = @invitation.blessings.new(
      name: params[:name],
      content: params[:content]
    )
    @success = @blessing.save
  end

  private

    def permitted_params
      params.permit!
    end
end

app/helpers/blessings_helper.rb
module BlessingsHelper
end

app/views/blessings/_form.html.erb
<%= form_for(@blessing) do |f| %>
  <% if @blessing.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@blessing.errors.count, "error") %> prohibited this blessing from being saved:</h2>

      <ul>
      <% @blessing.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :content %><br>
    <%= f.text_area :content %>
  </div>
  <div class="field">
    <%= f.label :name %><br>
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :invitation_id %><br>
    <%= f.text_field :invitation_id %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/blessings/edit.html.erb
<h1>Editing blessing</h1>

<%= render 'form' %>

<%= link_to 'Show', @blessing %> |
<%= link_to 'Back', blessings_path %>

app/views/blessings/index.html.erb
<h1>Listing blessings</h1>

<table>
  <thead>
    <tr>
      <th>Content</th>
      <th>Name</th>
      <th>Invitation</th>
      <th></th>
      <th></th>
      <th></th>
    </tr>
  </thead>

  <tbody>
    <% @blessings.each do |blessing| %>
      <tr>
        <td><%= blessing.content %></td>
        <td><%= blessing.name %></td>
        <td><%= blessing.invitation %></td>
        <td><%= link_to 'Show', blessing %></td>
        <td><%= link_to 'Edit', edit_blessing_path(blessing) %></td>
        <td><%= link_to 'Destroy', blessing, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Blessing', new_blessing_path %>

app/views/blessings/new.html.erb
<h1>New blessing</h1>

<%= render 'form' %>

<%= link_to 'Back', blessings_path %>

app/views/blessings/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Content:</strong>
  <%= @blessing.content %>
</p>

<p>
  <strong>Name:</strong>
  <%= @blessing.name %>
</p>

<p>
  <strong>Invitation:</strong>
  <%= @blessing.invitation %>
</p>

<%= link_to 'Edit', edit_blessing_path(@blessing) %> |
<%= link_to 'Back', blessings_path %>